### ISSUE TITLE
[Bug] Number value should be None instead of 0 when number input is emptied

### ISSUE THREAD

**Issue by lazyhope** [CrystalWindSnake/ex4nicegui#196]
Thanks for the quick fix. Here is another issue I found:

```python
from ex4nicegui import rxui, to_ref
from nicegui import ui

num = to_ref(None)
rxui.number(value=num)
ui.button('Increment', on_click=lambda: ui.notify(num.value))
ui.run()
```
When running the above code, filling some numbers and deleting them, `num` becomes 0 (instead of None) which is not expected.

**Comment by lazyhope** [comment]
Also, it would be great to support new display components like `ui.code`, `ui.markdown`, currently it seems we have no other options for text with styles.

**Comment by CrystalWindSnake** [comment]
@lazyhope  nice catch. I found that ui.number indeed returns 0 in the on_change event, not None. It appears the value should be retrieved from the component object itself rather than the event argument.

```python
# notify None when deleting value
ui.number(on_change=lambda e: ui.notify(e.value))
```

**Comment by lazyhope** [comment]
> @lazyhope nice catch. I found that ui.number indeed returns 0 in the on_change event, not None. It appears the value should be retrieved from the component object itself rather than the event argument.
> 
> ```python
> # notify 0 when deleting value
> ui.number(on_change=lambda e: ui.notify(e.value))
> ```

By the way, I found this was also the case for other input components like `rxui.input` and `rxui.textarea`

**Comment by CrystalWindSnake** [comment]
> > @lazyhope nice catch. I found that ui.number indeed returns 0 in the on_change event, not None. It appears the value should be retrieved from the component object itself rather than the event argument.
> > ```python
> > # notify 0 when deleting value
> > ui.number(on_change=lambda e: ui.notify(e.value))
> > ```
> 
> By the way, I found this was also the case for other input components like `rxui.input` and `rxui.textarea`

I'm not sure if this is a bug with NiceGUI.I've initiated a discussion in NiceGUI, but haven't received a response yet. Perhaps ex4nicegui could fix this issue internally .

**Comment by CrystalWindSnake** [comment]
> > > > @lazyhope nice catch. I found that ui.number indeed returns 0 in the on_change event, not None. It appears the value should be retrieved from the component object itself rather than the event argument.
> > > > ```python
> > > > # notify 0 when deleting value
> > > > ui.number(on_change=lambda e: ui.notify(e.value))
> > > > ```
> > > 
> > > 
> > > By the way, I found this was also the case for other input components like `rxui.input` and `rxui.textarea`
> > 
> > 
> > I'm not sure if this is a bug with NiceGUI.I've initiated a discussion in NiceGUI, but haven't received a response yet. Perhaps ex4nicegui could fix this issue internally .
> 
> Just as you said, maybe they just choose to use component value instead of event sender value, and I actually prefer their approach because it's easier to deal with a single None value than various other empty value like '' or 0 (not to mention its ambiguity with user entered 0)

However, even the input and textarea in NiceGUI have the same issue.

```python
def onchange(e):
    print(f"{e.sender.value=} {e.value=}")

ui.input(on_change=onchange)
```

**Comment by lazyhope** [comment]
You are right, I didn't notice that, in that case, I suppose that is not an issue then. Thanks!
