### ISSUE TITLE
[Bug] TypeError: Type is not JSON serializable: TabsBindableUi

### ISSUE THREAD

**Issue by lazyhope** [CrystalWindSnake/ex4nicegui#197]
`rxui.tabs` is not working properly:
```python
from ex4nicegui import rxui
from nicegui import ui

with rxui.tabs() as tabs:
    tab = rxui.tab("Tab 1")
with rxui.tab_panels(tabs):
    with rxui.tab_panel(tab):
        rxui.label("1")

ui.run()
```
Will raise `TypeError: Type is not JSON serializable: TabsBindableUi`
Might be related to #175

**Comment by lazyhope** [comment]
Cool! Thanks for the great work!

**Comment by CrystalWindSnake** [comment]
@lazyhope However, this might breaking change. Under the reactive mechanism, the correct usage of tabs and panels should be as :

```python
from ex4nicegui import rxui, to_ref
from nicegui import ui

# view data
tabs_options = ["Tab 1", "Tab 2", "Tab 3"]
current_tab = to_ref(tabs_options[0])

# ui
with rxui.tab_panels(current_tab):
    for tab in tabs_options:
        with rxui.tab_panel(tab):
            rxui.label(f"this is tab {tab}")

with rxui.tabs(current_tab) as tabs:
    for tab in tabs_options:
        rxui.tab(tab)

rxui.select(tabs_options, value=current_tab)
```

**Comment by lazyhope** [comment]
I see. I was actually trying to have multiple tabs whose label is bind to their corresponding states' `name` ref variable, could you please provide me an example where the value of input box in each tab will change the tab name?

**Comment by CrystalWindSnake** [comment]
> I see. I was actually trying to have multiple tabs whose label is bind to their corresponding states' `name` ref variable, could you please provide me an example where the value of input box in each tab will change the tab name?

like this?

```python

from ex4nicegui import rxui, to_ref, ref_computed
from nicegui import ui

# view data
tab_names = ["Tab 1", "Tab 2", "Tab 3"]
tab_labels = [to_ref(name) for name in tab_names]
current_tab = to_ref(tab_names[0])


@ref_computed
def select_options():
    return {name: label.value for name, label in zip(tab_names, tab_labels)}


# ui
with rxui.tab_panels(current_tab):
    for name, label in zip(tab_names, tab_labels):
        with rxui.tab_panel(name):
            rxui.label(lambda label=label: f"this is tab {label.value}")
            rxui.input("tab name:", value=label)


with rxui.tabs(current_tab) as tabs:
    for name, label in zip(tab_names, tab_labels):
        rxui.tab(name, label=label)

rxui.select(select_options, value=current_tab)
```

**Comment by lazyhope** [comment]
> > I see. I was actually trying to have multiple tabs whose label is bind to their corresponding states' `name` ref variable, could you please provide me an example where the value of input box in each tab will change the tab name?
> 
> like this?
> 
> ```python
> from ex4nicegui import rxui, to_ref, ref_computed
> from nicegui import ui
> 
> # view data
> tab_names = ["Tab 1", "Tab 2", "Tab 3"]
> tab_labels = [to_ref(name) for name in tab_names]
> current_tab = to_ref(tab_names[0])
> 
> 
> @ref_computed
> def select_options():
>     return {name: label.value for name, label in zip(tab_names, tab_labels)}
> 
> 
> # ui
> with rxui.tab_panels(current_tab):
>     for name, label in zip(tab_names, tab_labels):
>         with rxui.tab_panel(name):
>             rxui.label(lambda label=label: f"this is tab {label.value}")
>             rxui.input("tab name:", value=label)
> 
> 
> with rxui.tabs(current_tab) as tabs:
>     for name, label in zip(tab_names, tab_labels):
>         rxui.tab(name, label=label)
> 
> rxui.select(select_options, value=current_tab)
> ```

Exactly! Thank you for your time! Please feel free to close this issue.

**Comment by CrystalWindSnake** [comment]
Considering compatibility with Nicegui's usage, I will attempt to fix this issue in the future, provided it doesn't break the API.
