### ISSUE TITLE
Wired behaviour of deep dict ref variable's pop method

### ISSUE THREAD

**Issue by lazyhope** [CrystalWindSnake/ex4nicegui#224]
The following code has output that looks very confusing to me:
```python
from ex4nicegui import to_ref, effect
from nicegui import ui

states_dict = to_ref({"a": 3, "b": 4}, is_deep=True)
states_list = to_ref(["a", "b"], is_deep=True)

@effect
def show_dict():
    print(states_dict.value)
@effect
def show_list():
    print(states_list.value)


states_dict.value.pop("a")
states_list.value.remove("a")
states_dict.value.pop("b")
states_list.value.remove("b")


ui.run(show=False)
```
Output:
```
{'a': 3, 'b': 4}
['a', 'b']
['b']
[]
```

My expected output was:
```
{'b': 4}
['b']
{}
[]
```
Could you please explain whether this was a bug or not?

**Comment by CrystalWindSnake** [comment]
Thanks for reporting this issue,@lazyhope.
Yes, the proxy dictionary appears not set up to intercept and trigger on the `pop` method. This seems to be a bug within the [signe](https://github.com/CrystalWindSnake/py-signe) package.

The correct output should be:
```python
{'a': 3, 'b': 4} #
['a', 'b']

{'b': 4}
['b']
{}
[]
```

Note, the `effect` decorator will immediately invoke the method once in order to collect dependencies.

**Comment by CrystalWindSnake** [comment]
@lazyhope This issue has been resolved in the latest version of `sign`. Updating to version 0.4.15 should fix this problem.

```
pip install signe==0.4.15 
```

additionally, if you want the effect to trigger only when the value changes, you can use `on`, explicitly specifying the watched target, and setting the `onchanges` parameter to `True`

```
from ex4nicegui import to_ref, effect, on
from nicegui import ui

states_dict = to_ref({"a": 3, "b": 4}, is_deep=True)
states_list = to_ref(["a", "b"], is_deep=True)


@on(states_dict, onchanges=True)
def show_dict():
    print(states_dict.value)


@on(states_list, onchanges=True)
def show_list():
    print(states_list.value)


states_dict.value.pop("a")
states_list.value.remove("a")
states_dict.value.pop("b")
states_list.value.remove("b")

ui.run(show=False)
```

Output:
```
{'b': 4}
['b']
{}
[]
```

**Comment by lazyhope** [comment]
Excellent! Thanks for the quick fix!
